name: Mutiple Jobs Depedncy
run-name: ${{ github.actor }} multiple
on:
    push:
        paths:
            - '.github/workflows/depedent_jobs.yml'
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Creating a file
              run: touch File.txt
            - name: Uploading as artifact
              uses: actions/upload-artifact@v3
              with:
                name: Text File
                path: File.txt
    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: Download the uploaded artifact file from prevoius job
              uses: actions/download-artifact@v3 
              with:
                name: Text File
            - name: Accessing the file created in job1
              run: cat File.txt
    job3:
        runs-on: ubuntu-latest
        concurrency:
            group: prod
            cancel-in-progress: true
        steps:
            - name: "Job3"
              run: echo "pranjal"
    # job4:
    #     runs-on: ubuntu-latest
    #     concurrency:
    #         group: prod
    #         cancel-in-progress: true
    #     steps:
    #         - name: "Job4"
    #           run: echo "kjlnfwelfkm"

