name: Testing github context
run-name: ${{ github.actor }} total
on:
    push:
        paths:
            - '.github/workflows/github_context.yml'
    
jobs:
    context:
        runs-on: ubuntu-latest
        steps:
            - name: context
              run: ${{toJson(github.event_name)}}