name: Testing github context
run-name: ${{ github.actor }} is learning GitHub Actions
on:
    push
jobs:
    context:
        runs-on: ubuntu-latest
        steps:
            - name: context
              run: ${{toJson(github)}}