name: Docker Image CI for GHCR
run-name: ${{ github.actor }} is learning GitHub Actions
on:
    push:
        paths:
            - '.github/workflows/publish_ghcr.yml'
    schedule:
        - cron: "53 13 * * *"

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image Using secrets and varibles
              run: |
                docker login --username Pranjal-mukherjee --password ${{secrets.GH_PAT}} ghcr.io 
                docker build . --tag ghcr.io/${{vars.DOCKER_USERNAME}}/hello-world-ghcr:latest
                docker push ghcr.io/${{vars.DOCKER_USERNAME}}/hello-world-ghcr:latest           
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: '14'
            - name: Install Dependencies
              run: npm install

            - name: Run Test Cases
              run: npm test
    observe-status:
        needs: build_and_publish
        runs-on: ubuntu-latest

        steps:
            - name: Check Job Status
              run: "echo Job Status: ${{ job.status }}"
                 