name: creating a open pull request
run-name: ${{ github.actor }} event
on:
    pull_request:
        types: [opened,reopened,synchronize]
jobs:
    hello1:
        runs-on: ubuntu-latest
        steps:
            - name: see github events
              run: echo '${{toJson(github.event)}}' | jq
    