name: If Expression implemented
run-name: ${{ github.actor }} event
on:
    pull_request:
        paths:
            - '.github/workflows/pull_request.yml'
jobs:
    hello1:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: see github events
              run: echo '${{toJson(github.event)}}' | jq
    