name: Hello World Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: step1
              run: echo "Echo name"
              shell: bash 
